# -*- coding: utf-8 -*-
"""working_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdMqy-b_VnyCovsDK9hBKq1XVLvjXpui
"""

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
import math
from scipy.stats import qmc
import warnings
import time
import traceback

# Suppress runtime warnings during optimization
warnings.filterwarnings('error', category=RuntimeWarning)
warnings.filterwarnings('ignore')

# --- Data Values ---
years = [1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965]
rice_production = np.array([
    70850000, 78000000, 82500000, 86800000, 88000000,
    57635000, 55580000, 53366000, 65000000, 76500000,
    86000000, 87400000])
positive_rice_production = np.array([val * 0.8/ max(rice_production) for val in rice_production])

# Global failure tracking for debugging
failure_reasons = {"extinction": 0, "grain_survival": 0, "structural": 0, "locust_instability": 0, "start_gap": 0, "flatline": 0}

def system(t, y, Eh, *params):
    S, L, G = y
    lam, a2, b1, b3, b5, c1, c2, c3, r_g, K_l, a3 = params # Added a3 as a param

    b4 = 1
    b2 = 0.15 * b1
    c3 = 1

    current_Eh = Eh if 4.0 <= t <= 6.5 else 0.0

    def f(L):
        return b1 + (b2 * L**2) / (b3**2 + L**2)

    dS = (lam * S * L) / (K_l + L) + (a2 * G * S) - (a3 * S) - (current_Eh * S)
    dL = f(L) * L - (b4 * L) - (b5 * S * L)
    dG = (r_g * (1 - G)) - (c1 * G * S) - (c2 * G * L) - (c3 * G)

    return [dS, dL, dG]

numYears = 30
stepsPerYear = 30
t_span = (0, numYears)
t_eval = np.linspace(0, numYears, stepsPerYear * numYears)
params = [0.001, 0.00, 1.50, 0.01, 0.005, 0.001, 0.005, 0.05, 1.0, 5.0, 0.33]

def run_simulation(S0, L0, G0, Eh=0.0, graphSL=False, graphGrains=False, useChicago=True):
    y0 = [S0, L0, G0]
    sol = solve_ivp(system, t_span, y0, t_eval=t_eval, args=(Eh, *params), method='LSODA', atol=1e-9, rtol=1e-7)

    if graphSL:
        plt.figure(figsize=(8,5))
        plt.plot(sol.t, sol.y[0], label='Sparrows')
        plt.plot(sol.t, sol.y[1], label='Locusts')
        plt.xlabel('Time (years)'); plt.ylabel('Population Index')
        plt.legend(); plt.grid(True); plt.show()

    if graphGrains:
        plt.figure(figsize=(8,5))
        if useChicago:
            plt.plot(list(range(12)), positive_rice_production, 'o-', label='Chicago Rice Data')
        plt.plot(sol.t, sol.y[2], label='Grain')
        plt.legend(); plt.grid(True); plt.show()

    simGrains = sol.y[2]
    from sklearn.metrics import r2_score as r2
    grainsForFit = [simGrains[i] for i in range(0, 12 * stepsPerYear, stepsPerYear)]
    return r2(positive_rice_production, grainsForFit), simGrains

def run_lhs_simulations(n_samples_pass1=20000, n_samples_pass2=200):
    baseline_range = np.max(positive_rice_production[:4]) - np.min(positive_rice_production[:4])
    target_G0 = positive_rice_production[0]
    weight_fit, weight_osc = 0.70, 0.30

    def evaluate_params(param_set):
        global failure_reasons, params
        lam, a2, b1, b3, b5, c1, c2, c3, r_g, K_l, a3, Eh_val = param_set
        params = [lam, a2, b1, b3, b5, c1, c2, c3, r_g, K_l, a3]

        try:
            burn_sol = solve_ivp(system, (0, 30), [5.0, 10.0, 0.5], t_eval=t_eval, args=(0.0, *params), method='LSODA')
            if not burn_sol.success: return -float('inf'), None

            half = len(t_eval) // 2
            S_osc, L_osc, G_osc = burn_sol.y[0, half:], burn_sol.y[1, half:], burn_sol.y[2, half:]

            if np.min(S_osc) < 0.01 or np.min(L_osc) < 0.01:
                failure_reasons["extinction"] += 1
                return -float('inf'), None
            if np.mean(G_osc) < 0.4:
                failure_reasons["grain_survival"] += 1
                return -float('inf'), None
            if np.mean(L_osc) <= np.mean(S_osc):
                failure_reasons["structural"] += 1
                return -float('inf'), None
            if np.max(L_osc) > 100 * np.min(L_osc):
                failure_reasons["locust_instability"] += 1
                return -float('inf'), None

            sim_range = np.max(G_osc) - np.min(G_osc)
            osc_score = max(0, 1.0 - (sim_range / (2 * baseline_range))) if sim_range > baseline_range else 1.0
            best_p_score, best_p_start = -float('inf'), None

            found_start = False
            for idx in range(len(t_eval)-150, len(t_eval), 5):
                S0, L0, G0 = burn_sol.y[:, idx]
                if abs(G0 - target_G0) > 0.15: continue
                found_start = True

                fit, simGrains = run_simulation(S0, L0, G0, Eh=Eh_val)

                # Check for response to hunting
                if np.min(simGrains[120:195]) > (simGrains[0] * 0.99):
                    continue

                combined = (weight_fit * fit) + (weight_osc * osc_score)
                if combined > best_p_score:
                    best_p_score, best_p_start = combined, (S0, L0, G0)

            if not found_start: failure_reasons["start_gap"] += 1
            if found_start and best_p_score == -float('inf'): failure_reasons["flatline"] += 1

            return best_p_score, best_p_start

        except Exception:
            return -float('inf'), None

    print(f"Starting Pass 1 ({n_samples_pass1} samples)...")
    log_bounds = [
        (-1, 2.5), (-4, 0), (0.05, 1.2), (-3, -1), (-5, -0.3),
        (-5, -1), (-5, -1), (-3, 0), (-1, 1), (-1, 4), (-1, 0), (-1, 0.0)
    ]

    sampler1 = qmc.LatinHypercube(d=12) # Increased to 12
    scaled1 = qmc.scale(sampler1.random(n=n_samples_pass1), [b[0] for b in log_bounds], [b[1] for b in log_bounds])

    valid_count, best_s, best_p, best_m = 0, -float('inf'), None, None
    b1_mark = max(1, n_samples_pass1 // 10)

    for i, p_log in enumerate(scaled1):
        p = [10**x for x in p_log]
        score, start_vec = evaluate_params(p)
        if score > -float('inf'): valid_count += 1
        if score > best_s: best_s, best_p, best_m = score, p, start_vec
        if (i + 1) % b1_mark == 0:
            print(f"Pass 1: {((i + 1) // b1_mark) * 10}% complete. Valid: {valid_count}")
            print(f"  Failures -> Extinction: {failure_reasons['extinction']}, Structural: {failure_reasons['structural']}, Stability: {failure_reasons['locust_instability']}")

    if best_p is None: return None, None, None

    print(f"Pass 1 Best: {best_s:.4f}. Starting Pass 2...")
    l_bounds = [(x*0.7, x*1.3) for x in best_p]
    scaled2 = qmc.scale(qmc.LatinHypercube(d=12).random(n=n_samples_pass2), [b[0] for b in l_bounds], [b[1] for b in l_bounds])

    for i, p in enumerate(scaled2):
        score, start_vec = evaluate_params(p)
        if score > best_s: best_s, best_p, best_m = score, p, start_vec

    return best_p, best_s, best_m

if __name__ == "__main__":
    bestParams, finalScore, midpoint = run_lhs_simulations()
    if midpoint:
        print(bestParams)
        params = bestParams[:-1]
        print(f"\nOptimization Complete. Best Score: {finalScore}")

        print("\n--- Generating Hunting Simulation Graph ---")
        run_simulation(*midpoint, Eh=bestParams[-1], graphSL=True, graphGrains=True)

        print("\n--- Generating Baseline (No Hunting) Graph ---")
        run_simulation(*midpoint, Eh=0.0, graphSL=True, graphGrains=True)

